site_name: PrairieLearn
site_url: https://github.com/PrairieLearn/PrairieLearn
repo_url: https://github.com/PrairieLearn/PrairieLearn
theme: readthedocs
docs_dir: new_docs
# Fix "Edit on GitHub" link: (defaults to edit/master/docs/, note the s)
edit_uri: blob/master/docs/

extra_javascript:
  - mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

pages:
- Introduction:
  - 'What is PrairieLearn?': 'Introduction/index.md'
  - 'Request a course space': 'Introduction/requestCourseSpace/index.md'
  - 'License': 'Introduction/license.md'
  - 'News': 'Introduction/news_items.md'

- Instructor Manual:
  - Get Started:
    - Creating course content:
      - 'Overview': 'Instructor/getStarted/createCourseContent/overview.md'
      - 'Creating a course instance': 'Instructor/getStarted/createCourseContent/course_instance.md'
      - 'Creating questions': 'Instructor/getStarted/createCourseContent/create_question.md'
      - 'Create an assessment': 'Instructor/getStarted/createCourseContent/create_assessment.md'
    - 'Question Gallery': 'Instructor/getStarted/questionGallery/index.md'
    - 'Workshops': 'Instructor/getStarted/workshops/index.md'
    - 'Pitfalls': 'Instructor/getStarted/pitfalls/index.md'

  - How-to Guides:
    - Course Instances:
      - 'Create new course instance': 'Instructor/HowTos/createCourse.md'
      - 'Setup course access': 'Instructor/HowTos/courseAccess.md'
      - 'Copy course instance from previous term': 'Instructor/HowTos/howtoCopyCourseInstance.md'
    - Staff:
      - 'Give course content access': 'Instructor/HowTos/courseContentAccess.md'
      - 'Give student data access': 'Instructor/HowTos/studentDataAccess.md'
    - Assessments:
      - 'Create new assessment': 'Instructor/HowTos/createAssessment.md'
      - 'Setup time access': 'Instructor/HowTos/assessmentAccess.md'
      - 'Setup varying credit': 'Instructor/HowTos/assessmentCredit.md'
      - 'Add questions to an assessment': 'Instructor/HowTos/addQuestions.md'
      - 'Define bonus points': 'Instructor/HowTos/bonusPoints.md'
      - 'Randomize question ordering': 'Instructor/HowTos/howtoRandomizeOrder.md'
      - 'Organize questions into zones': 'Instructor/HowTos/howtoZones.md'
      - 'Create question pools': 'Instructor/HowTos/addQuestionPools.md'
      - 'Use best score from a zone': 'Instructor/HowTos/bestQuestion.md'

      - 'Creating Homework Sets': 'Instructor/HowTos/Assessments/howtoHomeworkSet.md'
      - 'Creating Assessment Sets': 'Instructor/HowTos/Assessments/howtoAddAssessmentSet.md'


      - 'Add text and links to assessments': 'Instructor/HowTos/Assessments/howtoAddTextLinks.md'
      - 'Change number of attempts': 'Instructor/HowTos/Assessments/howtoAttempts.md'
      - 'Collaborative Assessments': 'Instructor/HowTos/Assessments/howtoCollaborative.md'
      - 'Disable real-time grading': 'Instructor/HowTos/Assessments/howtoDisableRealTime.md'
      - 'Limit the rate for grading': 'Instructor/HowTos/Assessments/howtoLimitGradeRate.md'
      - 'Allow students to report issues': 'Instructor/HowTos/Assessments/howtoAllowIssues.md'
      - 'Allow multiple assessment instances': 'README.md'
      - 'Make a copy of an existing assessment': 'Instructor/HowTos/Assessments/howtoCopyAssessment.md'

    - Assement Examples:
      - 'Create a homework': 'README.md'
      - 'Create an Exam': 'Instructor/HowTos/Assessments/howtoExams.md'

    - Questions:
      - 'Create questions': 'README.md'
      - 'Randomizing Question Selection': 'Instructor/HowTos/howtoRandomizeQuestions.md'



  - References:

    - 'Installing and running PL locally': 'Instructor/references/installing.md'
    - 'Syncing course content': 'Instructor/references/sync.md'
    - 'Course configuration': 'Instructor/references/course.md'

    - 'Scoring system':  'README.md'
    - 'Course staff': 'Instructor/references/staff.md'
    - 'Course instance configuration': 'Instructor/references/courseInstance.md'
    - 'Assessment configuration': 'Instructor/references/assessment.md'
    - 'Question configuration': 'Instructor/references/question.md'
    - 'Elements for writing questions': 'Instructor/references/elements.md'
    - 'Access control': 'Instructor/references/accessControl.md'
    - 'Remote exams': 'Instructor/references/remoteExams.md'
    - 'clientFiles and serverFiles': 'Instructor/references/clientServerFiles.md'
    - 'UUIDs in JSON files': 'Instructor/references/uuid.md'
    - 'Regrading assessments': 'Instructor/references/regrading.md'
    - 'Element for drawing': 'Instructor/references/pl-drawing/index.md'
    - 'External Grading': 'Instructor/references/externalGrading.md'
    - 'Python Autograder': 'Instructor/references/python-grader/index.md'
    - 'C/C++ autograder': 'Instructor/references/c-grader/index.md'
    - 'Java autograder': 'Instructor/references/java-grader/index.md'
    - 'Workspaces': 'Instructor/references/workspaces.md'
    - 'Manual grading': 'Instructor/references/manualGrading.md'
    - 'What to Tell Students': 'Instructor/references/whatToTellStudents.md'
    - 'API': 'Instructor/references/api.md'

  - FAQ: 'Instructor/HowTos/faq.md'

- Student Manual:
  - Get Started:
    - 'Adding a course': 'Student/getStarted/addCourse/index.md'

- Developers Manual:
  - Get Started:
    - 'Installing with local source': 'Developer/getStarted/installingLocalSource/index.md'

- Administrative Manual:
  - Get Started:
    - 'Creating a course': 'Admin/getStarted/makeCourse/index.md'
