site_name: PrairieLearn
site_url: https://github.com/PrairieLearn/PrairieLearn
repo_url: https://github.com/PrairieLearn/PrairieLearn
theme: readthedocs
docs_dir: new_docs
# Fix "Edit on GitHub" link: (defaults to edit/master/docs/, note the s)
edit_uri: blob/master/docs/

extra_javascript:
  - mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

pages:
- Introduction:
  - 'What is PrairieLearn?': 'Introduction/index.md'
  - 'Request a course space': 'Introduction/requestCourseSpace/index.md'
  - 'License': 'Introduction/license.md'
  - 'News': 'Introduction/news_items.md'

- Instructor Manual:
  - Get Started:
    - Creating course content:
      - 'Overview': 'Instructor/getStarted/createCourseContent/overview.md'
      - 'Creating a course instance': 'Instructor/getStarted/createCourseContent/course_instance.md'
      - 'Creating questions': 'Instructor/getStarted/createCourseContent/create_question.md'
      - 'Create an assessment': 'Instructor/getStarted/createCourseContent/create_assessment.md'
      - 'What to tell students': 'Instructor/getStarted/createCourseContent/whatToTellStudents.md'
    - 'Question Gallery': 'Instructor/getStarted/questionGallery/index.md'
    - 'Workshops': 'Instructor/getStarted/workshops/index.md'
    - 'Pitfalls': 'Instructor/getStarted/pitfalls/index.md'

  - How-to Guides:
    - Course Instances:
      - 'Create new course instance': 'Instructor/HowTos/createCourse.md'
      - 'Setup course access': 'Instructor/HowTos/courseAccess.md'
      - 'Copy course instance from previous term': 'Instructor/HowTos/howtoCopyCourseInstance.md'
    - Staff:
      - 'Give course content access': 'Instructor/HowTos/courseContentAccess.md'
      - 'Give student data access': 'Instructor/HowTos/studentDataAccess.md'
    - Assessments:
      - 'Create new assessment': 'Instructor/HowTos/createAssessment.md'
      - 'Setup time access': 'Instructor/HowTos/assessmentAccess.md'
      - 'Select the assessment set': 'Instructor/HowTos/howtoSelectAssessmentSet.md'
      - 'Create new assessment sets': 'Instructor/HowTos/howtoAddAssessmentSet.md'
      - 'Setup varying credit': 'Instructor/HowTos/assessmentCredit.md'
      - 'Add questions to an assessment': 'Instructor/HowTos/addQuestions.md'
      - 'Define bonus points': 'Instructor/HowTos/bonusPoints.md'
      - 'Randomize question ordering': 'Instructor/HowTos/howtoRandomizeOrder.md'
      - 'Organize questions into zones': 'Instructor/HowTos/howtoZones.md'
      - 'Create question pools': 'Instructor/HowTos/addQuestionPools.md'
      - 'Use best score from a zone': 'Instructor/HowTos/bestQuestion.md'
      - 'Add text to assessment overview page': 'Instructor/HowTos/howtoAddTextLinks.md'
      - 'Upload files to your course': 'Instructor/HowTos/howtoUploadFiles.md'
      - 'Allow students to report issues': 'Instructor/HowTos/howtoAllowIssues.md'
      - 'Make a copy of an existing assessment': 'Instructor/HowTos/howtoCopyAssessment.md'
    - Questions:
      - 'Create questions': 'Instructor/HowTos/createQuestions.md'

    - Assement Examples:
      - 'Create a homework': 'README.md'
      - 'Create an Exam': 'Instructor/HowTos/howtoExams.md'
      - 'Create a group assessment': 'Instructor/HowTos/howtoCollaborative.md'
      - 'Create an assessment using workspace': 'README.md'
      - 'Change the number of attempts': 'Instructor/HowTos/howtoAttempts.md'
      - 'Disable real-time grading': 'Instructor/HowTos/howtoDisableRealTime.md'
      - 'Limit the auto-grading rate': 'Instructor/HowTos/howtoLimitGradeRate.md'
      - 'Allow multiple assessment instances': 'README.md'
      - 'Learn student names': 'Instructor/HowTos/howtoLearn'


  - References:
    - 'Creating course content from local PL':
      - 'Installing and running PL locally': 'Instructor/references/installing.md'
      - 'Syncing course content': 'Instructor/references/sync.md'
    - 'Course configuration': 'Instructor/references/course.md'
    - 'Course staff': 'Instructor/references/staff.md'
    - 'Course instance configuration': 'Instructor/references/courseInstance.md'
    - 'Assessment configuration': 'Instructor/references/assessment.md'
    - 'Question format': 'Instructor/references/newQuestion.md'
    - 'Question configuration': 'Instructor/references/question.md'
    - 'Scoring system':  'README.md'
    - 'Access control': 'Instructor/references/accessControl.md'
    - 'Remote exams': 'Instructor/references/remoteExams.md'
    - 'clientFiles and serverFiles': 'Instructor/references/clientServerFiles.md'
    - 'UUIDs in JSON files': 'Instructor/references/uuid.md'
    - 'Regrading assessments': 'Instructor/references/regrading.md'
    - 'Elements for writing questions': 'Instructor/references/elements.md'
    - 'Element for drawing': 'Instructor/references/pl-drawing/index.md'
    - 'External Grading': 'Instructor/references/externalGrading.md'
    - 'Built-in external autograders':
      - 'Python Autograder': 'Instructor/references/python-grader/index.md'
      - 'C/C++ autograder': 'Instructor/references/c-grader/index.md'
      - 'Java autograder': 'Instructor/references/java-grader/index.md'
    - 'Workspaces': 'Instructor/references/workspaces.md'
    - 'Manual grading': 'Instructor/references/manualGrading.md'
    - 'API': 'Instructor/references/api.md'
    - Deprecated Features:
      - 'Old v1/v2 question format': 'Instructor/references/oldQuestion.md'
      - 'Old PrairieDraw graphics': 'Instructor/references/PrairieDraw.md'


- Developers Manual:
  - References:
    - 'Developer guide': 'Developer/references/dev-guide.md'
    - 'Installing with local source': 'Developer/references/installingLocal.md'
    - 'Installing natively': 'Developer/references/installingNative.md'
    - 'Server configuration': 'Developer/references/configJson.md'
    - 'Docker packaging': 'Developer/references/docker.md'
    - 'Contributing to PL development': 'Developer/references/contributing.md'
    - 'Question element writing': 'Developer/references/devElements.md'
    - 'Element extensions': 'Developer/references/elementExtensions.md'
