site_name: PrairieLearn
site_url: https://github.com/PrairieLearn/PrairieLearn
repo_url: https://github.com/PrairieLearn/PrairieLearn
theme: readthedocs
docs_dir: new_docs
# Fix "Edit on GitHub" link: (defaults to edit/master/docs/, note the s)
edit_uri: blob/master/docs/

extra_javascript:
  - mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

pages:
- Introduction:
  - 'What is PrairieLearn?': 'Introduction/index.md'
  - 'License': 'Introduction/license.md'
  - 'News': 'Introduction/news_items.md'

- Instructor Manual:
  - Get Started:
    - 'Requesting your course space': 'Instructor/getStarted/requestCourseSpace/index.md'
    - Creating course content:
      - 'Overview': 'Instructor/getStarted/createCourseContent/overview.md'
      - 'Creating a course instance': 'Instructor/getStarted/createCourseContent/course_instance.md'
      - 'Creating questions': 'Instructor/getStarted/createCourseContent/create_question.md'
      - 'Create an assessment': 'Instructor/getStarted/createCourseContent/create_assessment.md' 
    - 'Question Gallery': 'Instructor/getStarted/questionGallery/index.md'
    - 'Workshops': 'Instructor/getStarted/workshops/index.md'
    - 'Pitfalls': 'Instructor/getStarted/pitfalls/index.md'
  - How-to Guides:
    - 'Adding Staff to Course Instance': 'Instructor/howTos/howtoAddUserRoles.md'
    - Assessments:
      - 'Add Assessment Sets': 'Instructor/HowTos/Assessments/howtoAddAssessmentSet.md'
      - 'Assessments': 'Instructor/HowTos/Assessments/howtoAttempts.md'
  - References:
    - 'Elements for writing questions': 'Instructor/references/elements.md'
    - 'Assessments': 'Instructor/references/assessment.md'

- Student Manual:
  - Get Started:
    - 'Adding a course': 'Student/getStarted/addCourse/index.md'

- Developers Manual:
  - Get Started:
    - 'Installing with local source': 'Developer/getStarted/installingLocalSource/index.md'

- Administrative Manual:
  - Get Started:
    - 'Creating a course': 'Admin/getStarted/makeCourse/index.md'
