name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        # # Checkout the PR HEAD commit instead of merge commit
        # ref: ${{ github.event.pull_request.head.sha }}
        # We need the whole history so we can diff against `master` in `build-plbase-if-needed.sh`
        fetch-depth: 0
    - name: Print SHA
      run: echo $GITHUB_SHA
    - name: Print GitHub Ref
      run: echo $GITHUB_REF
    - name: Print last 20 commits
      run: git log -n 20
    - name: Build the plbase docker image if needed
      run: sh ./tools/build-image-if-needed.sh images/plbase prairielearn/plbase
    - name: Build the grader-c docker image if needed
      run: sh ./tools/build-image-if-needed.sh graders/c prairielearn/grader-c
    - name: Build the grader-java docker image if needed
      run: sh ./tools/build-image-if-needed.sh graders/java prairielearn/grader-java
    - name: Build the grader-python docker image if needed
      run: sh ./tools/build-image-if-needed.sh graders/python prairielearn/grader-python
    - name: Build the grader-r docker image if needed
      run: sh ./tools/build-image-if-needed.sh graders/r prairielearn/grader-r
    - name: Build the workspace-desktop docker image if needed
      run: sh ./tools/build-image-if-needed.sh workspaces/desktop prairielearn/workspace-desktop
    - name: Build the workspace-jupyterlab docker image if needed
      run: sh ./tools/build-image-if-needed.sh workspaces/jupyterlab prairielearn/workspace-jupyterlab
    - name: Build the workspace-rstudio docker image if needed
      run: sh ./tools/build-image-if-needed.sh workspaces/rstudio prairielearn/workspace-rstudio
    - name: Build the workspace-xtermjs docker image if needed
      run: sh ./tools/build-image-if-needed.sh workspaces/xtermjs prairielearn/workspace-xtermjs
    - name: Build the testing docker image
      run: docker build -t pltest .
    - name: Start the container
      run: docker run -td --name=test_container pltest /bin/bash
    - name: Run the JavaScript linter
      run: docker exec test_container /PrairieLearn/docker/lint_js.sh
    - name: Run the Python linter
      run: docker exec test_container /PrairieLearn/docker/lint_python.sh
    - name: Run the JavaScript typechecker
      run: docker exec test_container /PrairieLearn/docker/typecheck_js.sh
    - name: Run the Python typechecker
      run: docker exec test_container /PrairieLearn/docker/typecheck_python.sh
    - name: Run the JavaScript tests
      run: docker exec test_container /PrairieLearn/docker/test_js.sh
      timeout-minutes: 30
    - name: Run the Python tests
      run: docker exec test_container /PrairieLearn/docker/test_python.sh
      timeout-minutes: 5
    - name: Copy code-coverage data out of container
      run: docker cp test_container:/PrairieLearn/coverage coverage
    - name: Send code-coverage data to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
      continue-on-error: true
    - name: Install dependencies on host
      run: yarn install --frozen-lockfile
    - name: Build executor image
      run: ./tools/executor/build.js
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push executor image to registries
      run: ./tools/executor/release.js
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
